src/cities/urls.py
from django.urls import path
from . import views
from .views import HomePageView, SearchResultsView
app_name = 'cities'
urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('', HomePageView.as_view(), name='home'),
     path('<int:city_id>/', views.description, name='description'),
]

src/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('cities/', include('cities.urls')),
]

src/cities/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    description = models.CharField(max_length=255, default='description')
    class Meta:
      verbose_name_plural = "cities"

    def __str__(self):
        return self.name

src/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
          return self.question_text
    def was_published_recently(self):
            return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
            return self.choice_text

src/cities/views.py
from django.db.models import Q
from django.views.generic import TemplateView, ListView
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render


from .models import City


class HomePageView(TemplateView):
    template_name = 'home.html'

class SearchResultsView(ListView):
    model = City
    template_name = 'search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = City.objects.filter(
            Q(name__icontains=query) | Q(country__icontains=query)
        )
        return object_list

def description(request, question_id):
    city = get_object_or_404(City, pk=city_id)
    return render(request, 'description.html', {'city': city})

src/polls/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})





def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

src/cities/templates/description.html
<h1>hello</h1><p>{{ city.city_description }}</p>

src/cities/templates/home.html
<h1>Search for a city</h1>

<form action="{% url 'search_results' %}" method="get">
    <input name="q" type="text" placeholder="Search...">
</form>

src/cities/templates/search_results.html
<h1>Search Results</h1>

<ul>
    {% for city in object_list %}
    <li>
        {{ city.name }}, {{ city.country }}
    </li>
    {% endfor %}
</ul>

src/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

src/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Question Index</title>
</head>
<body>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
</body>
</html>